import React from 'react';
import { Home, Utensils, Sparkles, Bell, MoreHorizontal } from 'lucide-react';
import type { Status } from '../data/kitchenData';
export function Phone({children}:{children:React.ReactNode}){return <div className="phone"><div className="status"><span>9:41</span><span>▴ ᯤ ▰</span></div>{children}</div>}
export function Screen({children,nav='dashboard'}:{children:React.ReactNode;nav?:string}){return <><main className="screen">{children}</main><BottomNav active={nav}/></>}
export function Card({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`card ${className}`}>{children}</section>}
export function StatusPill({status,label}:{status:Status|'cyan';label?:string}){return <span className={`pill ${status==='critical'?'red':status}`}>{label||status}</span>}
export function Brand(){return <div className="brand">Kitchen<span>IQ</span></div>}
export function BottomNav({active}:{active:string}){const items=[['dashboard',Home,'Dashboard'],['dishes',Utensils,'Dishes'],['autopilot',Sparkles,'Autopilot'],['alerts',Bell,'Alerts'],['more',MoreHorizontal,'More']];return <nav className="nav">{items.map(([id,Icon,label]:any)=><button key={id} className={active===id?'active':''}><Icon size={16}/><span>{label}</span></button>)}</nav>}
export function Progress({value,color='var(--cyan)'}:{value:number;color?:string}){return <div className="bar"><span style={{width:`${value}%`,background:color}}/></div>}
export function StatTile({n,label,type}:{n:string|number;label:string;type:Status}){return <div className={`card ${type==='critical'?'red':type}`} style={{padding:12,textAlign:'center',background:`var(--${type==='critical'?'red':type}-soft)`}}><div style={{fontSize:20,fontWeight:800}}>{n}</div><div className="meta" style={{color:'inherit'}}>{label}</div></div>}
export function Sparkline(){return <svg className="sparkline" viewBox="0 0 220 46"><path d="M2 35 L28 25 L54 28 L80 18 L106 24 L132 14 L158 20 L186 11 L218 4" fill="none" stroke="var(--cyan)" strokeWidth="3" strokeLinecap="round"/><path d="M2 35 L28 25 L54 28 L80 18 L106 24 L132 14 L158 20 L186 11 L218 4 L218 46 L2 46Z" fill="rgba(63,198,240,.12)"/></svg>}
export function Gauge({value}:{value:number}){const r=72,c=2*Math.PI*r,off=c*(1-value/100);return <div style={{display:'grid',placeItems:'center',height:190}}><svg width="190" height="190" viewBox="0 0 190 190"><circle cx="95" cy="95" r={r} stroke="rgba(255,255,255,.08)" strokeWidth="13" fill="none"/><circle cx="95" cy="95" r={r} stroke="var(--cyan)" strokeWidth="13" fill="none" strokeLinecap="round" strokeDasharray={c} strokeDashoffset={off} transform="rotate(135 95 95)"/><text x="95" y="98" textAnchor="middle" fill="var(--text)" fontSize="34" fontWeight="800">{value}%</text><text x="95" y="124" textAnchor="middle" fill="var(--green)" fontSize="12" fontWeight="700">+4.2% vs LW</text></svg></div>}
